#!/bin/bash
# Goal to Go

trap "/usr/bin/killall -q -u $USER TwoMinute 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stderr=/dev/null ./TwoMinute 1 5 5 20 < /dev/null

# clean up temp file
cd ..
rm -rf temp
